secrets:
  onesignal: a
  facebookAppId: a
  googleMapsApiKey: a
  recaptcha: a
  googleAnalyticsCode: a
  googleAppId: a
  googleWebAppId: a
  linkedInAppId: a
  linkedInRedirectUri: a

urls:
  api: a
  web: a
  mobile: a
  protocol: a
  CDN: a
  imageCDN: a
  videoCDN: a

endpoints: {
  appInfo: /app/info|get
  phoneExists: /phones/exists|get,
  firebaseConfirm: /phones/firebase/confirm|post

  reset: /auth/reset|post
  register: /auth/register|post
  login: /auth/login|post
  socialLogin: /auth/social|post
  linkedInAuth: /auth/linkedin/access|post
  logout: /auth/logout|post

  getCurrentUser: /users/current|get,

  getSingleAddress: /addresses/single|get
